sudo: false
language: perl
perl:
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
cache:
  directories:
    - local

install:
  - make -f ci.mk travis-install
script:
  - make -f ci.mk travis-script
after_success:
  - make -f ci.mk travis-after-success
